### ISSUE TITLE
I'm running on an M1 Macbook and keep getting "zsh: segmentation fault" in terminal when I try to run 'adb devices'

### ISSUE THREAD

**Issue by magictheblathering** [philips/inkpalm-5-adb-english#3]
Title. Can't seem to find a guide to do this on Mac, and the nuanced differences are creating errors.

Thanks so much for your effort on this.

**Comment by philips** [comment]
A segmentation fault is a memory error. It maybe an incompatibility between the Android tools and M1 Macs. It works fine on my Intel Mac
