### ISSUE TITLE
Have a few questions for owners of this device

### ISSUE THREAD

**Issue by vdurante** [philips/inkpalm-5-adb-english#4]
Hey, I am deciding between the inkpalm and Poke 4 Lite. I have a few questions, if someone mind answering them, would be very thankful?

- is everything in english with this patch?
- Does this device support google play store?
- If not, can I sideload all the apps?

**Comment by philips** [comment]
Not everything is in english.  But enough to get by. 

Yes sideload works. It doesnt have google play services.
